name: Build documentation

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install wget
        run: sudo apt-get update; sudo apt-get install wget

      - name: Install templtr
        run: |
          wget https://github.com/saile515/templtr/releases/latest/download/templtr-x64-linux.tar.gz
          tar -xvzf templtr-x64-linux.tar.gz
        
      - name: Build docs
        run: cd docs; ../templtr build -b /templtr
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/out
